export { productosRepository } from './productos.repository'
export { cajerosRepository }  from './cajeros.repository'
export { ventasRepository }    from './ventas.repository'
export { clientesRepository }  from './clientes.repository'
export { mesasRepository }     from './mesas.repository'
export { configRepository }    from './config.repository'
export { ordenesRepository }   from './ordenes.repository'
